### PR TITLE
[PM-3021] Add support for Browser in /e/ OS

### PR DESCRIPTION
**Pull request by althafvly**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [x] Other

## Objective

Add support for [/e/ OS browser ](https://gitlab.e.foundation/e/os/browser).

## Code changes

Add foundation.e.browser as supported package.

* **file.ext:** Description of what was changed and why

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

**Comment by althafvly** [comment]
Link to browser apk and build tool

https://gitlab.e.foundation/e/os/browser
https://gitlab.e.foundation/e/os/android_prebuilts_prebuiltapks_lfs/-/tree/main/Browser

**Comment by althafvly** [comment]
Hello @fedemkr, I hope you're doing well. I wanted to follow up on this pull request. It's been almost six months since this PR made, and I was wondering if there's anything specific holding it back from being merged?

**Comment by dbosompem** [comment]
Hi @althafvly thanks for following up. The team is making some significant changes to our mobile app, and is evaluating how we want to handle browser support PRs. I will get back to you shortly on this. Thanks for your patience!

**Comment by althafvly** [comment]
closed without even an explanation?. It's been open for a year now.

**Comment by althafvly** [comment]
> Hi @althafvly thanks for following up. The team is making some significant changes to our mobile app, and is evaluating how we want to handle browser support PRs. I will get back to you shortly on this. Thanks for your patience!

Please give explanation?, its closed for some reason. It's been open for a year now.

**Comment by althafvly** [comment]
Attaching link to the commit https://github.com/althafvly/mobile/commit/c4ebb21fd3e693cb36e62fa5a238dfa67e75c64d

**Pull request closed without merging**
