### PR TITLE
[PM-9328] Codeowners setup

### PR DESCRIPTION
**Pull request by vvolkgang**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-9328

## 📔 Objective

Adds repository codeowners. Due to a GitHub Teams restriction we're not able to create a team for LiveFront devs, in order to continue being able to review and approve PRs they'll need to be individually named in this file. 

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by fedemkr — DISMISSED** [review]

**Review by fedemkr — DISMISSED** [review]

**Review by SaintPatrck — APPROVED** [review]
LGTM.

@david-livefront @brian-livefront, are you all okay with these users being included in CODEOWNERS?

**Comment by brian-livefront** [comment]
@SaintPatrck I'd say for now, yes.

**Comment by brian-livefront** [comment]
@vvolkgang Are we ever going to uncomment the per-feature-team setup in the rest of the file or is that just something we'd want to remove at some point?

**Comment by vvolkgang** [comment]
> @vvolkgang Are we ever going to uncomment the per-feature-team setup in the rest of the file or is that just something we'd want to remove at some point?

Left it in place because we're not sure yet.

**Comment by brian-livefront** [comment]
@vvolkgang OK sounds good.

**Review by SaintPatrck — APPROVED** [review]

**Pull request merged**
