### PR TITLE
PM-10855: Update the minimum SDK to API 29 (Android 10)

### PR DESCRIPTION
**Pull request by david-livefront**
## 🎟️ Tracking

[PM-10855](https://bitwarden.atlassian.net/browse/PM-10855)

## 📔 Objective

This PR updates the minimum SDK to API 29 (Android 10).

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-10855]: https://bitwarden.atlassian.net/browse/PM-10855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SaintPatrck — APPROVED** [review]

**Review by brian-livefront — APPROVED** [review]

**Comment by david-livefront** [comment]
Thanks @SaintPatrck & @brian-livefront

**Comment by jvschiavo** [comment]
What should I do to keep using the Bitwarden app on an Android 9 smartphone?

**Comment by maxkpower** [comment]
> What should I do to keep using the Bitwarden app on an Android 9 smartphone?

Hey @jvschiavo,
security support for Android 9 officially ended in January 2022. We don't recommend using Bitwarden on devices that don't receive security updates anymore. That said, you can still use older APK versions or access your vault through the web vault if absolutely needed.

**Comment by pamperer562580892423** [comment]
> That said, you can still use older APK versions

@maxkpower Are you sure those would still work with the current BW server versions? (thinking of _breaking changes_...)

**Comment by jvschiavo** [comment]
> That said, you can still use older APK versions or access your vault through the web vault if absolutely needed.

I think I tried using an older version of the app and it didn't work either. It couldn't connect to the server. I'll guess I'll have to rely on the web vault through the browser. Thanks. :)

**Comment by pamperer562580892423** [comment]
> It couldn't connect to the server. I'll guess I'll have to rely on the web vault through the browser.

@jvschiavo Keep in mind that web vault may also become inaccessible on older / unsupported browsers.

PS: I don't find the corresponding comment by @trmartin4 at the moment. But I think you could test this by e.g. installing Firefox 115 ESR. From what I know, you'll see that the web vault will not be accessible then. (I think currently the web vault requires at least Firefox 130 ESR)

**Comment by jvschiavo** [comment]
> > It couldn't connect to the server. I'll guess I'll have to rely on the web vault through the browser.
> 
> @jvschiavo Keep in mind that web vault may also become inaccessible on older / unsupported browsers.
> 
> PS: I don't find the corresponding comment by @trmartin4 at the moment. But I think you could test this by e.g. installing Firefox 115 ESR. From what I know, you'll see that the web vault will not be accessible then. (I think currently the web vault requires at least Firefox 130 ESR)

That is not a problem, I'm using Fennec, version 151.0.3, from F-Droid. :)

**Comment by pamperer562580892423** [comment]
@jvschiavo Good luck. I wish I had your audaciousness. - Android 9 got its [last security update over four years ago](https://android.googlesource.com/platform/build/+/refs/tags/android-security-9.0.0_r76).

**Comment by jvschiavo** [comment]
> @jvschiavo Good luck. I wish I had your audaciousness. - Android 9 got its [last security update over four years ago](https://android.googlesource.com/platform/build/+/refs/tags/android-security-9.0.0_r76).

The problem is the companies are always forcing us into buying new phones, when our old ones are working completely fine (minus the security part, which is exactly the problem). My relative is still rocking a 9 year old phone, the Xiaomi Mi A1, from 2017. It is working perfectly fine and does everything they need it to do. I just wish the companies still released security updates for them. We don't have this problem on PCs, using some distro like Debian I get support for 20+ years old computers just fine. But I digress.

**Pull request merged**
