### PR TITLE
[PM-1568] Support Mulch browser for autofill

### PR DESCRIPTION
**Pull request by fd1f**
## Type of change
- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [X] Other

## Objective
This PR adds the Mulch to the autofill whitelist.

## Code changes

* src/Android/Accessibility/AccessibilityHelpers.cs
* src/Android/Autofill/AutofillHelpers.cs
* src/Android/Resources/xml/autofillservice.xml

All to add Mulch support.

### CODE REVIEW

**Comment by bepoli** [comment]
Is this ever going to be merged?
Maybe we need to add some context, since devs may not be aware of Mulch:
[Mulch browser](https://divestos.org/pages/our_apps#mulch) is a chromium-based browser developed and maintained by the Divest Computing Group (the same devs of Mull browser, aka us.spotco.fennec_dos, currently supported by Bitwarden).
It is relevant since many users moved from Bromite (a browser currently supported by Bitwarden) to Mulch when the former [stopped receiving security updates](https://divestos.org/misc/ch-dates.txt).

**Comment by unoukujou** [comment]
Somebody please add this. Thanks.

**Comment by streetsamurai00mi** [comment]
waiting for this to be merged

**Review by yoshiz44 — APPROVED** [review]

**Review by yoshiz44 — APPROVED** [review]

**Comment by dbosompem** [comment]
Hi All, apologies for the long review time. This has been approved by Product Management, and so Engineering will pick this up and assist till it's merged. Thank you for the patience!

**Review by D3SOX — APPROVED** [review]

**Comment by D3SOX** [comment]
Hate to be that kind of guy but are there any updates on this? Merging this 5 line PR would save me and other Mulch users hours of time. I'm thinking about compiling it myself now.

**Pull request closed without merging**
